version: '3.1'

services:
  db:
    build: ./db-files
    hostname: db
    restart: always
    env_file:
      - .env
    volumes:
      - postgresVolume:/var/lib/postgresql/data

  minio:
    image: minio/minio
    hostname: minio
    env_file:
      - .env
    command: server /data
    volumes:
      - /mnt/data:/data

  server:
    build: ./server
    restart: always
    depends_on:
      - db
      - minio
    env_file:
      - .env

  client:
    build: ./client
    restart: always
    depends_on:
      - server

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - server
      - minio
      - db

volumes:
  postgresVolume: