version: '3.1'

services:
  db:
    build: ./db-files
    hostname: db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - nginx-proxy-network
    volumes:
      - postgresVolume:/var/lib/postgresql/data

  minio:
    image: minio/minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    command: server /data
    networks:
      - nginx-proxy-network
    volumes:
      - /mnt/data:/data

  server:
    build: ./server
    restart: always
    ports:
      - "5000:5000"
    networks:
      - nginx-proxy-network
    depends_on:
      - db
      - minio
    command: uvicorn src.application:fastApiServer --host localhost --port 5000

  client:
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    networks:
      - nginx-proxy-network
    depends_on:
      - server

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx-proxy-network
    depends_on:
      - client
      - server
      - minio
      - db

networks:
  nginx-proxy-network:
    external: true

volumes:
  postgresVolume: