version: '3.1'

services:
  db:
    build: ./db-files
    restart: always
    env_file:
      - ./server/src/settings/.env
    ports:
      - "5433:5433"
    volumes:
      - postgresVolume:/var/lib/postgresql/data

  server:
    build: ./server
    restart: always
    ports:
      - "5000:5000"

  client:
    build: ./client
    restart: always
    ports:
      - "3000:3000"

volumes:
  postgresVolume: