version: '3.1'

services:
  db:
    build: ./db-files
    hostname: db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgresVolume:/var/lib/postgresql/data
    networks:
      - nginx-proxy-network

  minio:
    image: minio/minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    command: server /data
    volumes:
      - /mnt/data:/data
    networks:
      - nginx-proxy-network

  server:
    build: ./server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
      - minio
    env_file:
      - .env
    command: uvicorn src.application:fastApiServer --host 0.0.0.0 --port 5000
    networks:
      - nginx-proxy-network

  client:
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server
    env_file:
      - .env
    networks:
      - nginx-proxy-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - server
    networks:
      - nginx-proxy-network

volumes:
  postgresVolume:

networks:
  nginx-proxy-network:
    external: true