version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres@localhost
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5431:5431"

  server:
    build: ./server
    restart: always
    ports:
      - "5000:5000"

  client:
    build: ./client
    restart: always
    ports:
      - "3000:3000"
